default:
  app_name: Sonar-DashBoard
  app_key: "xCklKxpabzc6olrXJ6922gwuOUQWXsI0EBnM7DR28kH8UIxF5xhnl47xvm3MGMEUrGopFys12M9Kps85EfK7VWgN3MY3KBnLXWGWDj7ZEEkst6GKqsK8ANz0Erj7ghrRvOHx0Y8758IoTRK5T9apL_eP3NHGcCdRB0YXIin6H2vYWM1eQjDkk9pmewek9HIhg0UGGOqkfL9WfAtTyoSiVQ5UWuwj78Dyq-6gZitHRIU"
  restAPI_port: "4000"
  registered_user: "Greg Pearson"
  registered_email: "gregpearson41@gmail.com"
  swagger_on: true
  sonarQube_account_token: 'squ_0f46d756dffa89b8b54339eb1e95ba5cb817cf61'
  sonarQube_server: 'http://172.24.1.159'
  sonarQube_port: "9000"
  web_host: http://localhost
  web_port: "3000"
  dataBase_host: '172.24.1.159'
  dataBase_name: 'nodeJWT'
  dataBase_port: 5432
  dataBase_user: 'postgres'
  dataBase_password: 'password'
